## Tomcat
#server:
#  port: 8718
#  servlet:
#    encoding:
#      enabled: true
#      force: true
#      charset: UTF-8
#    session:
#      cookie:
#        name: sentinel_dashboard_cookie
#logging:
#  level:
#    org:
#      springframework:
#        web: INFO
#  file:
#    name: ${user.home}/logs/csp/sentinel-dashboard.log
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#auth:
#  filter:
#    exclude-urls: "/,/auth/login,/auth/logout,/registry/machine,/version"
#    exclude-url-suffixes: "htm,html,js,css,map,ico,ttf,woff,png"
#  username: sentinel
#  password: sentinel
#sentinel:
#  dashboard:
#    version: ${project.version}
## Spring
#spring:
#  application:
#    # 应用名称
#    name: ruoyi-sentinel
#  profiles:
#    # 环境配置
#    active: dev
#  cloud:
#    nacos:
#      discovery:
#        # 服务注册地址
#        server-addr: 175.25.50.135:8848
#      config:
#        # 配置中心地址
#        server-addr: 175.25.50.135:8848
#        # 配置文件格式
#        file-extension: yml
#        # 共享配置
#        shared-configs:
#          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}