#eureka server端口
server:
  port: 8763

spring:
  application:
    name: eureka-server   #应用名称，在Eureka中作为服务名称

#eureka客户端配置（和Server交互） ,Eureka Server 其实也是一个Client
eureka:
  instance:
    hostname: localhost   #当前eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}   #实例名称

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#    register-with-eureka: true   #当前自己就是server，不需要注册自己
#    fetch-registry: true   #查询获取注册中心的服务信息，自己就是Server，不需要从Eureka server获取服务信息
