server:
  port: 8601

spring:
  application:
    name: stream-consumer

  cloud:
    stream:
      binders:    #绑定mq服务信息
        rabbitBinder:   #名称定义，用于后面的关联
          type: rabbit
          environment:    #mq环境配置
            spring:
              rabbitmq:
                host: 192.168.23.128
                port: 5672
                username: guest
                password: guest

      bindings: # 关联整合通道和binder对象
        myChannel-in-0:  # output是我们定义的通道名称，此处不能乱改
          destination: exchange # 要使用的Exchange名称（消息队列主题名称）
          content-type: application/json # application/json # 消息类型设置，比如json
          binder: rabbitBinder # 关联MQ服务
          group: default
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
  instance:
    prefer-ip-address: true #使用ip注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}   #实例名称


